const TodoConstants = {
  ADD_TASK: 'ADD_TASK',
  EDIT_TASK: 'EDIT_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_TASKS_COMPLETED: 'REMOVE_TASKS_COMPLETED',
  TOGGLE_TASK: 'TOGGLE_TASK',
  TOGGLE_TASKS: 'TOGGLE_TASKS'
};

export default TodoConstants;
